name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: push
jobs:
  clusters:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.clusters.outputs.test }}
    steps:
      - id: clusters
        run: echo "clusters=['eu', 'us']" >> $GITHUB_OUTPUT
  deploy:
    needs: clusters
    name: ${{ matrix.cluster }} deploy

    strategy:
      matrix: ${{ fromJSON(needs.clusters.outputs.clusters) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ ${{ matrix.cluster }} job's status is ${{ job.status }}."